config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'tags/:tag', to: 'posts#index', as: :tag

  resources :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  validates :content, presence: true

  acts_as_taggable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :update, :show, :destroy]

  def index
    @posts = if params[:tag]
      Post.tagged_with(params[:tag]).paginate(:page => params[:page]).order('id DESC')
    else
      Post.page(params[:page]).order('created_at DESC').per_page(4)
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save(post_params)
      flash[:success] = "Successfully created post!"
      redirect_to posts_path
    else
      flash[:error] = "Error creating new post!"
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      flash[:success] = "Successfully updated post!"
      redirect_to post_path(@post)
    else
      flash[:error] = "Error updating post!"
      render :edit
    end
  end

  def show
  end

  def destroy
    if @post.destroy
      flash[:success] = "Successfully deleted post!"
      redirect_to posts_path
    else
      flash[:error] = "Error deleting post!"
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :tag_list)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis
  def full_title(page_title)
    base_title = "Tags App"

    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav>
    <ul class="nav navbar-nav navbar-fixed-bottom">
      <li><%= link_to (image_tag("github_icon.png")), "https://github.com/arialblack14", target: "_blank" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
    <div class="container">
      <%= link_to "tag app", root_path , id: "logo" %>
      <nav>
        <ul class="nav navbar-nav pull-right">
          <li><%= link_to "Posts",   posts_path %></li>
        </ul>
      </nav>
    </div>
  </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= render 'shared/flash_messages' unless flash.empty? %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  <!-- hide flash notifications -->
  <script type="text/javascript">
  window.setTimeout(function() {
    $(".alert").fadeTo(500, 0).slideUp(500, function() {
      $(this).remove();
    });
  }, 3000);
  </script>
</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :title, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.input :content, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.input :tag_list, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.button :submit  %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= provide(:title, "Edit post") %>
<h2>Edit Post</h2>

<%= render "posts/form" %>

app/views/posts/index.html.erb
<div class="container">
  <div class="col-sm-10 col-sm-offset-1 col-xs-12 blog-content">
    <div id="tag_cloud">
      <% tag_cloud Post.tag_counts, %w[s m l] do |tag, css_class| %>
        <%= link_to tag.name, tag_path(tag.name), class: css_class %>
      <% end %>
    </div>

    <% @posts.each do |post| %>
    <div class="col-xs-12">
      <div class="text-center">
        <h2><%= link_to post.title, post_path(post) %></h2>
      </div>

      <div>
        <%= raw(post.content).truncate(400) %>
        <p class="time-created">Posted: <%= time_ago_in_words(post.created_at) %> ago</p>
      </div>

      <div>
        <p>Tags: <%= raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>
      </div>
    </div>
    <% end %>

    <div class="pagination">
    <% if @posts.any? %>
      <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
    <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<% provide(:title, "New post") %>
<h2>Create New Post</h2>
<%= render "posts/form" %>

app/views/posts/show.html.erb
<div class="col-sm-11 col-xs-12 blog-content">
  <h2 class="text-center">
    <%= @post.title %>
  </h2>

  <h5 class="text-center">
    <%= @post.created_at.strftime('%d %b %Y') %></h5>
  </h5>

  <div><%= raw @post.content %></div>

  <%= link_to edit_post_path(@post), class: "btn btn-default pull-right post-buttons" do %>
    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
  <% end %>
  <%= link_to post_path(@post), method: :delete, data: { confirm: "Are you sure?" },
                                class: "btn btn-default pull-right post-buttons" do %>
    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
  <% end %>
</div>

app/views/shared/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
<% end %>

app/views/shared/flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center jumbotron">
  <h1>Welcome to the Tag App</h1>
  <p>
  This is the home page for a simple article tagging app by Alex Tsiras.
  </p>
  <%= link_to("Post an article", new_post_path , class: "btn btn-lg btn-default post-buttons") %>
</div>
<div>
  <p>Check out all posts <%= link_to "here", posts_path %>.</p>
</div>